### ISSUE TITLE
websockets: Strip headers which should not be forwarded

### ISSUE THREAD

**Issue by pwaller** [scraperwiki/tiny-ssl-reverse-proxy#10]
Currently a load of headers get doubly-specified on the outbound websocket connection. We should remove hop-by-hop headers like a good reverse proxy citizen. Here's how the main one works:

https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L90-L101
https://github.com/golang/go/blob/master/src/net/http/httputil/reverseproxy.go#L164-L179

**Comment by drj11** [comment]
Example of headers that are sent:

```
GET /status/500 HTTP/1.1
Host: localhost:10443
User-Agent: Go 1.1 package http
Connection: Upgrade
Connection: Upgrade
Origin: //localhost:10443
Sec-Websocket-Key: G6mEHn8UzehM4fCh8pczdg==
Sec-Websocket-Key: AMmqVPxpUBK9IteLngPQgQ==
Sec-Websocket-Version: 13
Sec-Websocket-Version: 13
Upgrade: websocket
Upgrade: websocket
X-Forwarded-For: 127.0.0.1
```
